"""

Create a function that generates a random password. The password generated by the function
must have the following characteristics:
a. Length between 8 and 12 characters
b. Use at least one uppercase character, a number and a symbol. The function must be able to
generate passwords containing more than one character of these types, not just a single one
of each type.

"""

import random


def generate_password():
    length = random.randint(8, 12)

    uppercase_character = random.randint(1, length - 2)

    number = random.randint(1, length - 1 - uppercase_character)

    symbol = length - uppercase_character - number

    uppercase_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

    numbers = "1234567890"

    symbols = "@#*`´-_:,"

    l = [uppercase_character, number, symbol]
    m = [uppercase_characters, numbers, symbols]
    password = ""
    for i in range(3):
        while l[i] > 0:
            password += m[i][random.randint(0, len(m[i]) - 1)]
            l[i] -= 1

    return password


print(generate_password())
